### ISSUE TITLE
Add policy for merging codelist changes

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/Unofficial-Codelists#15]
At the moment, for Unofficial Codelists, when there is an automated PR, @andylolz and I are requested to approve a PR and then normally the other one of us merges the PR.

I think we should agree a faster process, at least for the GLIDE codes, whereby the same person can both approve and merge a PR. We could perhaps restrict this initially to codelists where we are just merging in changes that are made at source, so there is no controversy.

Either way, we should add an explanation of the process in README.md

wdyt @andylolz ?

**Comment by andylolz** [comment]
Yep, v good plan.

I’ve added branch protection on both repos, so that automatic checks **must pass** before a PR can be merged.

For GLIDE changes, I currently eyeball the change but don’t do much more than check for green ticks. I wonder if we should auto-merge if checks pass?
