### ISSUE TITLE
Work out how these should be named when they are IATI third party codelists

### ISSUE THREAD

**Issue by matmaxgeds** [codeforIATI/Unofficial-Codelists#3]
i.e. how is someone going to know which one to download?

**Comment by andylolz** [comment]
Not sure I understand this one, @matmaxgeds… Does it just refer to the category?

https://github.com/codeforIATI/IATI-Codelists-Extra/blob/e30275f31c1e0b71b2708bc6b6b03e20c1e76cf3/xml/HumanitarianGlobalClusters.xml#L8-L10

**Comment by matmaxgeds** [comment]
I think it is just because I don't understand how IATI codelists work i.e. when e.g. d-portal sees some data with @vocabuary=10, I know that means that it should lookup the code for the sector on the codelist that I decided to call HumanitarianGlobalClusters......but I am not sure how D-portal would know what codelist to use.....hence me wondering if the name that should be used for the codelist is not specified somewhere i.e. in a mapping table which says sector/@vocabulary=10 >> HumanitarianGobal Clusters......and hence I should not have just made the name up?

**Comment by andylolz** [comment]
> if the name that should be used for the codelist is not specified somewhere i.e. in a mapping table which says sector/@vocabulary=10 >> HumanitarianGobal Clusters

Yep, that’s exactly right. There’s a list of mappings here:
https://github.com/codeforIATI/Unofficial-Codelists/blob/master/mapping.xml

So as long as the codelist names we use are the same as the ones we use in this mappings file, we’re fine.
